/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekti;

/**
 *
 * @author RT
 */

import java.io.*;
import java.sql.*;
import javax.swing.ImageIcon;

public class BF extends javax.swing.JInternalFrame {

    private static final char [] x = {'0','1','2','3','4','5','6','7','8','9','a', 'b', 'c', 'd', 'e', 'f',
        'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A' ,'B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q'
		,'R','S','T','U','V','W','X','Y','Z'};
    
    private Connection con = null;
    private ResultSet rs = null;
    private PreparedStatement ps = null;
    
    public BF() {
        initComponents();
        con = SqlConnection.connect();
        //jLabel4.setIcon( new ImageIcon("giphy.gif"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Username");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Attack");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton1.setText("Password length 5");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton2.setText("Password length 6");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton3.setText("Password length 7");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton4.setText("All password");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Stop");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox1.setText("Check most common passwords");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("->");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(228, 228, 228)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(272, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(238, 238, 238)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(262, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jTextField1)))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addGap(8, 8, 8)
                .addComponent(jCheckBox1)
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(264, 264, 264))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(373, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(283, 283, 283)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(383, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(273, 273, 273)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Login.jTextField1.setText(jTextField1.getText());
        //BruteForce.bF();

        if(jCheckBox1.isSelected())
        {
            System.out.println("hej");
            if(passwords())
            {
                return;
            }
        }

        String pw = null;

        if(jRadioButton1.isSelected() || jRadioButton4.isSelected())
        {
            for(int i = 0; i<x.length;i++)
            {
                //pw = x[i];
                pw = Character.toString(x[i]);
                for(int j = 0; j < x.length;j++)
                {
                    pw += x[j];
                    for(int z=0; z<x.length;z++)
                    {
                        pw += x[z];
                        for(int l=0; l<x.length;l++)
                        {
                            pw += x[l];
                            for(int b=0; b<x.length;b++)
                            {
                                pw += x[b];
                                System.out.println(pw);
                                String q = "Select emri, pw from Personi where emri = '"+jTextField1.getText()+"' and pw ='"+pw+"'";
                                try{
                                    ps = con.prepareStatement(q);
                                    rs = ps.executeQuery();

                                    if(rs.next())
                                    {
                                        jLabel3.setText(pw);
                                        jLabel4.setIcon( new ImageIcon("tumblr_n6xniaz8sU1tti3jlo1_500"));
                                        //alarm();
                                        return;
                                    }
                                }
                                catch(SQLException e){}
                                pw =removeLastChar(pw);
                                //pw.replace(Character.toString(pw.charAt(pw.length()-1)), "");
                            }
                            pw = removeLastChar(pw);
                            //pw.replace(Character.toString(pw.charAt(pw.length()-1)), "");
                            //pw.replace(pw.substring(0,pw.length()-1), "");
                        }
                        pw = removeLastChar(pw);
                        //pw.replace(Character.toString(pw.charAt(pw.length()-1)), "");
                        //pw.replace(pw.substring(0,pw.length()-1), "");
                    }
                    pw = removeLastChar(pw);
                    //pw.replace(Character.toString(pw.charAt(pw.length()-1)), "");
                    //pw.replace(pw.substring(0,pw.length()-1), "");
                }
                pw = removeLastChar(pw);
                //pw.replace(Character.toString(pw.charAt(pw.length()-1)), "");
                //pw.replace(pw.substring(0,pw.length()-1), "");
            }
        }
        if(jRadioButton2.isSelected() || jRadioButton4.isSelected())
        {
            for(int i = 0; i<x.length;i++)
            {
                //pw = x[i];
                pw = Character.toString(x[i]);
                for(int j = 0; j < x.length;j++)
                {
                    pw += x[j];
                    for(int z=0; z<x.length;z++)
                    {
                        pw += x[z];
                        for(int l=0; l<x.length;l++)
                        {
                            pw += x[l];
                            for(int k = 0; k<x.length;k++)
                            {
                                pw += x[k];
                                for(int b=0; b<x.length;b++)
                                {
                                    pw += x[b];
                                    System.out.println(pw);
                                    String q = "Select emri, pw from Personi where emri = '"+jTextField1.getText()+"' and pw ='"+pw+"'";
                                    try{
                                        ps = con.prepareStatement(q);
                                        rs = ps.executeQuery();

                                        if(rs.next())
                                        {
                                            jLabel3.setText(pw);
                                            jLabel4.setIcon( new ImageIcon("tumblr_n6xniaz8sU1tti3jlo1_500.gif"));
                                            //alarm();
                                            return;
                                        }
                                    }
                                    catch(SQLException e){}
                                    pw =removeLastChar(pw);
                                    //pw.replace(Character.toString(pw.charAt(pw.length()-1)), "");
                                }
                                pw = removeLastChar(pw);
                            }
                            pw = removeLastChar(pw);
                            //pw.replace(Character.toString(pw.charAt(pw.length()-1)), "");
                            //pw.replace(pw.substring(0,pw.length()-1), "");
                        }
                        pw = removeLastChar(pw);
                        //pw.replace(Character.toString(pw.charAt(pw.length()-1)), "");
                        //pw.replace(pw.substring(0,pw.length()-1), "");
                    }
                    pw = removeLastChar(pw);
                    //pw.replace(Character.toString(pw.charAt(pw.length()-1)), "");
                    //pw.replace(pw.substring(0,pw.length()-1), "");
                }
                pw = removeLastChar(pw);
                //pw.replace(Character.toString(pw.charAt(pw.length()-1)), "");
                //pw.replace(pw.substring(0,pw.length()-1), "");
            }
        }
        if(jRadioButton3.isSelected() || jRadioButton4.isSelected())
        {
            for(int i = 0; i<x.length;i++)
            {
                //pw = x[i];
                pw = Character.toString(x[i]);
                for(int j = 0; j < x.length;j++)
                {
                    pw += x[j];
                    for(int z=0; z<x.length;z++)
                    {
                        pw += x[z];
                        for(int l=0; l<x.length;l++)
                        {
                            pw += x[l];
                            for(int k = 0; k<x.length;k++)
                            {
                                pw += x[k];
                                for(int w = 0;w<x.length;w++)
                                {
                                    pw += x[w];
                                    for(int b=0; b<x.length;b++)
                                    {
                                        pw += x[b];
                                        System.out.println(pw);
                                        String q = "Select emri, pw from Personi where emri = '"+jTextField1.getText()+"' and pw ='"+pw+"'";
                                        try{
                                            ps = con.prepareStatement(q);
                                            rs = ps.executeQuery();

                                            if(rs.next())
                                            {
                                                jLabel3.setText(pw);
                                                jLabel4.setIcon( new ImageIcon("tumblr_n6xniaz8sU1tti3jlo1_500.gif"));
                                                //alarm();
                                                return;
                                            }
                                        }
                                        catch(SQLException e){}
                                        pw =removeLastChar(pw);
                                        //pw.replace(Character.toString(pw.charAt(pw.length()-1)), "");
                                    }
                                    pw = removeLastChar(pw);
                                }
                                pw = removeLastChar(pw);
                            }
                            pw = removeLastChar(pw);
                            //pw.replace(Character.toString(pw.charAt(pw.length()-1)), "");
                            //pw.replace(pw.substring(0,pw.length()-1), "");
                        }
                        pw = removeLastChar(pw);
                        //pw.replace(Character.toString(pw.charAt(pw.length()-1)), "");
                        //pw.replace(pw.substring(0,pw.length()-1), "");
                    }
                    pw = removeLastChar(pw);
                    //pw.replace(Character.toString(pw.charAt(pw.length()-1)), "");
                    //pw.replace(pw.substring(0,pw.length()-1), "");
                }
                pw = removeLastChar(pw);
                //pw.replace(Character.toString(pw.charAt(pw.length()-1)), "");
                //pw.replace(pw.substring(0,pw.length()-1), "");
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private static String removeLastChar(String s) {
        
        String substring = null;
        if(s != null)
        {
            substring = s.substring(0,s.length()-1);
        }
        return substring;
    }  
    
    
    public boolean passwords()
    {
        try
        {
            BufferedReader br = new BufferedReader(new FileReader(new File("Passwords.txt")));
            String s = "";
            
            while((s = br.readLine()) != null)
            {
                System.out.println(s);
                String q = "Select emri, pw from Personi where emri = '"+jTextField1.getText()+"' and pw ='"+s+"'";
                try
                {
                    ps = con.prepareStatement(q);
                    rs = ps.executeQuery();
                    if(rs.next())
                    {
                        jLabel3.setText(s);
                        jLabel4.setIcon( new ImageIcon("tumblr_n6xniaz8sU1tti3jlo1_500.gif"));
                        //alarm();
                        return true;
                    }
                }catch(SQLException e){}
            }
        }
        catch(IOException e){}
        
        return false;
    }
    
    
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected())
        {
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected())
        {
            jRadioButton1.setSelected(false);
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton3.isSelected())
        {
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(false);
            jRadioButton4.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton4.isSelected())
        {
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jButton1.isSelected())
        {
            jButton1.setSelected(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
